const MAKE_A_NEW_ORDER = 'MAKE_A_NEW_ORDER';
const SET_ORDER_STATUS = 'SET_ORDER_STATUS';
const SET_ORDER_PRICE = 'SET_ORDER_PRICE';
const SET_PIZZA_SIZE = 'SET_PIZZA_SIZE';
const SET_CHEESE_RAND = 'SET_CHEESE_RAND';
const ADD_TOPPING_TO_PIZZA = 'ADD_TOPPING_TO_PIZZA';
const REMOVE_TOPPING_FROM_PIZZA = 'REMOVE_TOPPING_FROM_PIZZA';
